#!/bin/bash

#how to use
if [ "$#" -lt 2 ]; 
then
	echo "Usage: network_directory backend (optinal: debug)"
	exit 1
fi

source scripts/includes.sh


#args
net_dir=$1
backend=$2
debug=$3

network_name=$(basename $net_dir)

###run test
echo "Running ${bold}$(basename $executable)${normal} with the network ${bold}$network_name${normal} using the backend ${bold}$backend${normal}."

solver=$(find $net_dir -name "solver.prototxt")

output=$(file_name $net_dir $backend $debug)

echo "output file: $output"
echo "solver: $solver"

#run the program
$executable $solver $backend 2>&1 | tee $output
	
echo "output saved to $output"
#result
if [ ${PIPESTATUS[0]} -eq 0 ]; then
	echo "Run using the solver ${bold}$(basename $2)${normal}: SUCCESS!"
	#plot_name="$backend\_$(basename $output).pdf"
else
	#echo "Printing last 30 lines of $output:"
	#tail -n 30 $output 
	echo "Run using the solver ${bold}$(basename $2)${normal}: FAILURE!"
fi


if [[ -z "$debug" ]];
then
	echo "plotting"
	#python scripts/plot.py $output #plot_name
else
	#for debuging
	echo "debug plotting"
	#python scripts/debug_plot.py $output #plot_name
fi


#create data dir if it does not exist
mkdir -p $net_dir/data

#remove old data and plots
#rm -f $net_dir/*.dat $net_dir/*.plot

draw_line 
